[package]
name = "ton_api"
version = "0.2.110"
authors = [
    "Aaron Gallagher <_@habnab.it>",
    "Connie Hilarides <connorcpu@live.com>",
    "Denis K. <denis.k@tonlabs.io>",
    "Alexey Vavilin <alexey.v@tonlabs.io",
]
description = "Minimal wrappers for TON serialization using TL-schema"
edition = "2018"

[dependencies]
byteorder = "1.4"
extfmt = "0.1"
failure = "0.1"
lazy_static = "1.4"
ordered-float = "2.8"
serde = "1.0"
serde_derive = "1.0"
secstr = "0.4"
hex = "0.4"

ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[build-dependencies]
failure = "0.1.7"
serde_json = "1.0.52"

[build-dependencies.ton_tl_codegen]
#default-features = false
path = "../ton_tl_codegen"
